### ISSUE TITLE
Active Tabs are not rendering border-bottom-color properly

### ISSUE THREAD

**Issue by jonathasbsouza** [vtex/styleguide#1236]
**Describe the bug**
We have defined the active tab border-bottom-color to be .b--emphasis (#F71963) but the browser renders another color (#962442). This behavior occurs whatever color we choose.

**To Reproduce**
Go to [Tabs in styleguide docs](https://styleguide.vtex.com/#/Components/Navigation/Tabs)

**Expected behavior**
To active tab border-bottom-color be #F71963

**Screenshots**
<img width="611" alt="Screen Shot 2020-06-03 at 18 36 46" src="https://user-images.githubusercontent.com/7189694/83780356-71d55180-a663-11ea-8d48-4d6db356512d.png">

**Comment by estacioneto** [comment]
Pro tip: `border-bottom-style: solid;` ✨

**Comment by gtkatakura** [comment]
The problem is because `chrome` use `border-style: outset;` by default for `button`, we need to set `border-style: solid;` to have the same color in all sides.

![Screenshot from 2020-06-18 14-40-56](https://user-images.githubusercontent.com/8618687/85053976-be478380-b171-11ea-945a-ee7340e5fe36.png)

`Input` use `border-style: inset;`, so probably we need always to use explicit the `border-style: solid'` when we need always to have the same color in all sides of the element.

**Comment by estacioneto** [comment]
That's it. And not only Chrome does that. Safari does that too (don't know about Firefox though).
