### ISSUE TITLE
Button in-line styling does not apply

### ISSUE THREAD

**Issue by oviolion** [vtex/styleguide#1341]
**Describe the bug**
You cannot add in-line styling to the <Button /> component

**To Reproduce**
<Button style={{ margin: 8 }} /> doesn't add any margin

**Expected behavior**
<Button style={{ margin: 8 }} /> should add margin: 8px any margin

**Comment by kevinch** [comment]
Hey @oviolion thanks for the report. 
Indeed our components do not accept any kind of customisation and that's by design. Since this styleguide is mostly used with our admin apps, we wanted at the time to limit the customisation to ensure consistency and not risk strange stylings. We've learned along the way and realised that this was not necessarily the best approach but since the whole styleguide is built that way, this refactor would be too much work to handle. I suggest to wrap your component within a parent `div` for example and apply the margin on this one.
Thanks.

**Comment by oviolion** [comment]
Thought so, thank you for the explanation 😄
