### ISSUE TITLE
Toast allows message prop to be a node, but PropTypes requires string

### ISSUE THREAD

**Issue by ericreis** [vtex/styleguide#608]
**Describe the bug**
The PropTypes of the **Toast** component requires the message prop to be a string, but it works when passing a node.

This is useful when we need to format the message.

**To Reproduce**

**Expected behavior**
Be able to use a node as the message of the *Toast* without raising PropTypes error.

**Screenshots**

**Additional context**

**Comment by emersonlaurentino** [comment]
@ericreis This behavior is correct, you should only pass a `string` as an argument of the` showToast` function.

To solve your problem with `react-intl`, you should use the [intl.formatMessage](https://github.com/formatjs/react-intl/blob/master/docs/API.md#formatmessage) function instead of using the component `FormattedMessage`.
